[package]
name = "serde_chainpack"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.10.1"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "1.0"
byteorder = "1.4"
serde_bytes = "0.11"
chrono = { version = "0.4" }
